name: profind_api
version: 0.0.1
description: ProFind API
homepage: homepage

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.1 <5.0.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'
  chopper: ^4.0.1
  json_annotation: ^4.4.0

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  test: ^1.16.0
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.4
  swagger_dart_code_generator: ^2.4.6
