name: profindweb
description: Hiring made easier

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui: ^3.12.0
  openapi_generator_annotations: ^1.1.4
  url_launcher: ^6.1.5
  universal_html: ^2.0.8
  webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  openapi_generator: ^1.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/landing-page/en/
    - assets/landing-page/es/